version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_LOCAL_PORT}:${DB_DOCKER_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${DB_DOCKER_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      PORT: ${BACKEND_PORT}
      CLIENT_URL: ${CLIENT_URL}
    depends_on:
      - postgresdb
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    # command: sh -c "npm run setup-db && node dist/server.js"

  frontend:
    build:
      context: ./frontend
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      PORT: ${FRONTEND_PORT}
    ports:
      - '${FRONTEND_PORT}:80'
    depends_on:
      - backend

volumes:
  postgres_data:
